//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE2Reference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExchangeInfoResponse", Namespace="http://www.serviceobjects.com")]
    public partial class ExchangeInfoResponse : object
    {
        
        private PE2Reference.ExchangeInfo[] ExchangeInfoResultsField;
        
        private PE2Reference.PE2Error ErrorField;
        
        private string[] DebugField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PE2Reference.ExchangeInfo[] ExchangeInfoResults
        {
            get
            {
                return this.ExchangeInfoResultsField;
            }
            set
            {
                this.ExchangeInfoResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public PE2Reference.PE2Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string[] Debug
        {
            get
            {
                return this.DebugField;
            }
            set
            {
                this.DebugField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PE2Error", Namespace="http://www.serviceobjects.com")]
    public partial class PE2Error : object
    {
        
        private string TypeField;
        
        private string TypeCodeField;
        
        private string DescField;
        
        private string DescCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TypeCode
        {
            get
            {
                return this.TypeCodeField;
            }
            set
            {
                this.TypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Desc
        {
            get
            {
                return this.DescField;
            }
            set
            {
                this.DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DescCode
        {
            get
            {
                return this.DescCodeField;
            }
            set
            {
                this.DescCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExchangeInfo", Namespace="http://www.serviceobjects.com")]
    public partial class ExchangeInfo : object
    {
        
        private string PhoneNumberField;
        
        private string NameField;
        
        private string CityField;
        
        private string StateField;
        
        private string CountryField;
        
        private string LineTypeField;
        
        private string TimeZoneField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        private string SMSAddressField;
        
        private string MMSAddressField;
        
        private PE2Reference.PortedInfo PortedInfoField;
        
        private string NoteCodesField;
        
        private string NoteDescriptionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string LineType
        {
            get
            {
                return this.LineTypeField;
            }
            set
            {
                this.LineTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TimeZone
        {
            get
            {
                return this.TimeZoneField;
            }
            set
            {
                this.TimeZoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SMSAddress
        {
            get
            {
                return this.SMSAddressField;
            }
            set
            {
                this.SMSAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string MMSAddress
        {
            get
            {
                return this.MMSAddressField;
            }
            set
            {
                this.MMSAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public PE2Reference.PortedInfo PortedInfo
        {
            get
            {
                return this.PortedInfoField;
            }
            set
            {
                this.PortedInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string NoteCodes
        {
            get
            {
                return this.NoteCodesField;
            }
            set
            {
                this.NoteCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string NoteDescriptions
        {
            get
            {
                return this.NoteDescriptionsField;
            }
            set
            {
                this.NoteDescriptionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PortedInfo", Namespace="http://www.serviceobjects.com")]
    public partial class PortedInfo : object
    {
        
        private string OriginalNameField;
        
        private string OriginalLineTypeField;
        
        private string PortedDateField;
        
        private string LATAField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OriginalName
        {
            get
            {
                return this.OriginalNameField;
            }
            set
            {
                this.OriginalNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OriginalLineType
        {
            get
            {
                return this.OriginalLineTypeField;
            }
            set
            {
                this.OriginalLineTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PortedDate
        {
            get
            {
                return this.PortedDateField;
            }
            set
            {
                this.PortedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LATA
        {
            get
            {
                return this.LATAField;
            }
            set
            {
                this.LATAField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternationalExchangeInfoResponse", Namespace="http://www.serviceobjects.com")]
    public partial class InternationalExchangeInfoResponse : object
    {
        
        private PE2Reference.InternationalExchangeInfo InternationalExchangeInfoField;
        
        private PE2Reference.PE2Error ErrorField;
        
        private string[] DebugField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PE2Reference.InternationalExchangeInfo InternationalExchangeInfo
        {
            get
            {
                return this.InternationalExchangeInfoField;
            }
            set
            {
                this.InternationalExchangeInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public PE2Reference.PE2Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string[] Debug
        {
            get
            {
                return this.DebugField;
            }
            set
            {
                this.DebugField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InternationalExchangeInfo", Namespace="http://www.serviceobjects.com")]
    public partial class InternationalExchangeInfo : object
    {
        
        private string NumberInField;
        
        private string CountryCodeField;
        
        private string FormatNationalField;
        
        private string ExtensionField;
        
        private string LocalityField;
        
        private string LocalityMatchLevelField;
        
        private string TimeZoneField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        private string CountryField;
        
        private string CountryISO2Field;
        
        private string CountryISO3Field;
        
        private string FormatInternationalField;
        
        private string FormatE164Field;
        
        private string CarrierField;
        
        private string LineTypeField;
        
        private string SMSAddressField;
        
        private string MMSAddressField;
        
        private bool IsValidField;
        
        private bool IsValidForRegionField;
        
        private string NoteCodesField;
        
        private string NoteDescriptionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberIn
        {
            get
            {
                return this.NumberInField;
            }
            set
            {
                this.NumberInField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string FormatNational
        {
            get
            {
                return this.FormatNationalField;
            }
            set
            {
                this.FormatNationalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Extension
        {
            get
            {
                return this.ExtensionField;
            }
            set
            {
                this.ExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Locality
        {
            get
            {
                return this.LocalityField;
            }
            set
            {
                this.LocalityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string LocalityMatchLevel
        {
            get
            {
                return this.LocalityMatchLevelField;
            }
            set
            {
                this.LocalityMatchLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string TimeZone
        {
            get
            {
                return this.TimeZoneField;
            }
            set
            {
                this.TimeZoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string CountryISO2
        {
            get
            {
                return this.CountryISO2Field;
            }
            set
            {
                this.CountryISO2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string CountryISO3
        {
            get
            {
                return this.CountryISO3Field;
            }
            set
            {
                this.CountryISO3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string FormatInternational
        {
            get
            {
                return this.FormatInternationalField;
            }
            set
            {
                this.FormatInternationalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string FormatE164
        {
            get
            {
                return this.FormatE164Field;
            }
            set
            {
                this.FormatE164Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string Carrier
        {
            get
            {
                return this.CarrierField;
            }
            set
            {
                this.CarrierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string LineType
        {
            get
            {
                return this.LineTypeField;
            }
            set
            {
                this.LineTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string SMSAddress
        {
            get
            {
                return this.SMSAddressField;
            }
            set
            {
                this.SMSAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string MMSAddress
        {
            get
            {
                return this.MMSAddressField;
            }
            set
            {
                this.MMSAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public bool IsValid
        {
            get
            {
                return this.IsValidField;
            }
            set
            {
                this.IsValidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public bool IsValidForRegion
        {
            get
            {
                return this.IsValidForRegionField;
            }
            set
            {
                this.IsValidForRegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string NoteCodes
        {
            get
            {
                return this.NoteCodesField;
            }
            set
            {
                this.NoteCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string NoteDescriptions
        {
            get
            {
                return this.NoteDescriptionsField;
            }
            set
            {
                this.NoteDescriptionsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.serviceobjects.com", ConfigurationName="PE2Reference.IPE2Soap")]
    public interface IPE2Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPE2Soap/GetExchangeInfo", ReplyAction="http://www.serviceobjects.com/IPE2Soap/GetExchangeInfoResponse")]
        System.Threading.Tasks.Task<PE2Reference.ExchangeInfoResponse> GetExchangeInfoAsync(string PhoneNumber, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IPE2Soap/GetInternationalExchangeInfo", ReplyAction="http://www.serviceobjects.com/IPE2Soap/GetInternationalExchangeInfoResponse")]
        System.Threading.Tasks.Task<PE2Reference.InternationalExchangeInfoResponse> GetInternationalExchangeInfoAsync(string PhoneNumber, string Country, string LicenseKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IPE2SoapChannel : PE2Reference.IPE2Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class PE2SoapClient : System.ServiceModel.ClientBase<PE2Reference.IPE2Soap>, PE2Reference.IPE2Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PE2SoapClient() : 
                base(PE2SoapClient.GetDefaultBinding(), PE2SoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DOTSPhoneExchange2.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PE2SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PE2SoapClient.GetBindingForEndpoint(endpointConfiguration), PE2SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PE2SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PE2SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PE2SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PE2SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PE2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PE2Reference.ExchangeInfoResponse> GetExchangeInfoAsync(string PhoneNumber, string LicenseKey)
        {
            return base.Channel.GetExchangeInfoAsync(PhoneNumber, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<PE2Reference.InternationalExchangeInfoResponse> GetInternationalExchangeInfoAsync(string PhoneNumber, string Country, string LicenseKey)
        {
            return base.Channel.GetInternationalExchangeInfoAsync(PhoneNumber, Country, LicenseKey);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DOTSPhoneExchange2))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DOTSPhoneExchange2))
            {
                return new System.ServiceModel.EndpointAddress("https://sws.serviceobjects.com/PE2/soap.svc/soap");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PE2SoapClient.GetBindingForEndpoint(EndpointConfiguration.DOTSPhoneExchange2);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PE2SoapClient.GetEndpointAddress(EndpointConfiguration.DOTSPhoneExchange2);
        }
        
        public enum EndpointConfiguration
        {
            
            DOTSPhoneExchange2,
        }
    }
}
